import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import AdUnit from '@/components/AdUnit'
import NDAGeneratorClient from '@/components/tools/NDAGeneratorClient'
import ToolInfo from '@/components/ToolInfo'
import RelatedTools from '@/components/RelatedTools'
import { createMetadata, createToolSchema, createFAQSchema } from '@/lib/metadata'

export const metadata = createMetadata({
  title: 'NDA Generator',
  description: 'Generate custom Non-Disclosure Agreement (NDA) templates online. Free NDA generator with customizable terms, duration, and confidentiality clauses for business protection.',
  keywords: 'NDA generator, non-disclosure agreement, confidentiality agreement template, legal document generator, NDA template, business NDA',
  url: 'https://calcuzy.app/nda-generator',
  image: '/og-tools.png',
})

export default function NDAGeneratorPage() {
  const structuredData = createToolSchema({
    name: 'NDA Generator',
    description: 'Generate custom Non-Disclosure Agreement templates with customizable terms and confidentiality clauses',
    url: 'https://calcuzy.app/nda-generator',
    category: 'UtilityApplication',
    features: ['Unilateral & mutual NDAs', 'Custom duration terms', 'Confidentiality clauses', 'PDF export', 'Business-ready templates']
  })

  const faqData = [
    {
      question: 'What is a Non-Disclosure Agreement (NDA)?',
      answer: 'An NDA is a legally binding contract that establishes confidentiality between parties. It protects sensitive business information, trade secrets, and proprietary data from being shared with unauthorized parties. NDAs are commonly used in business negotiations, employment, and partnerships.'
    },
    {
      question: 'Is the NDA generated by this tool legally binding?',
      answer: 'The NDA template provides a solid foundation for a legally valid agreement when properly executed according to your jurisdiction\'s laws. However, we strongly recommend having an attorney review any legal document before signing, especially for high-stakes business situations.'
    },
    {
      question: 'What is the difference between unilateral and mutual NDAs?',
      answer: 'A unilateral NDA protects information shared by only one party (common in employer-employee situations). A mutual NDA protects confidential information exchanged by both parties, which is typical in partnerships, joint ventures, or merger discussions.'
    },
    {
      question: 'How long should an NDA last?',
      answer: 'NDA duration varies by situation. Common terms range from 1-5 years for business negotiations, while trade secrets may require indefinite protection. Consider the nature of your confidential information when choosing duration.'
    }
  ]

  const faqSchema = createFAQSchema(faqData)

  const steps = [
    { title: 'Enter Party Details', description: 'Provide names and contact information for all parties involved in the agreement.' },
    { title: 'Define Confidential Information', description: 'Specify what types of information will be protected under the NDA.' },
    { title: 'Set Duration & Terms', description: 'Choose the agreement duration and any specific obligations or restrictions.' },
    { title: 'Generate & Download', description: 'Create your NDA template ready for review, customization, and signing.' }
  ]

  const tips = [
    'Be specific about what constitutes confidential information to avoid disputes',
    'Include clear definitions of permitted uses and restrictions',
    'Consider adding provisions for return or destruction of materials upon termination',
    'Always have legal counsel review important NDAs before signing',
    'Keep signed copies securely stored for future reference'
  ]

  return (
    <div className="min-h-screen bg-primary-bg fade-in">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <Navbar />
      
      <main className="container section-responsive">
        <div className="text-center mb-16 slide-up">
          <h1 className="heading-1 text-center mb-6">
            NDA Generator
          </h1>
          <p className="paragraph text-center max-w-3xl mx-auto mb-8">
            Generate a professional Non-Disclosure Agreement template for your business needs. 
            Customize terms, duration, and confidentiality requirements in minutes.
          </p>
        </div>

        <AdUnit slot={1} />

        <div className="max-w-4xl mx-auto fade-in-up">
          <NDAGeneratorClient />
        </div>

        <AdUnit slot={2} />

        <div className="mt-16 fade-in-up">
          <ToolInfo
            title="NDA Generator"
            description={
              <>
                <p className="mb-4">
                  A Non-Disclosure Agreement (NDA) is a legal contract that establishes confidential 
                  relationships between parties. It outlines what information is considered confidential, 
                  obligations to protect that information, and remedies for breaches.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                  <div className="bg-blue-50 p-4 rounded-xl border border-blue-100">
                    <h4 className="font-semibold text-blue-800 mb-2">📄 Unilateral NDA</h4>
                    <p className="text-sm text-blue-700">
                      One party shares confidential information. Common in employer-employee relationships.
                    </p>
                  </div>
                  <div className="bg-emerald-50 p-4 rounded-xl border border-emerald-100">
                    <h4 className="font-semibold text-emerald-800 mb-2">🤝 Mutual NDA</h4>
                    <p className="text-sm text-emerald-700">
                      Both parties exchange confidential information. Used in partnerships and joint ventures.
                    </p>
                  </div>
                </div>
              </>
            }
            steps={steps}
            faqs={faqData}
            tips={tips}
          />
        </div>

        <AdUnit slot={3} />

        <div className="max-w-4xl mx-auto mt-12 fade-in-up">
          <RelatedTools currentTool="/nda-generator" category="generators" />
        </div>
      </main>

      <Footer />
    </div>
  )
}
